name: "Close finished milestones"
on:
  schedule:
  - cron: 0/5 * * * *

jobs:
  milestone-closer:
    runs-on: ubuntu-latest
    steps:
    - name: Milestone closer message
      run: echo Checking for milestones to close
    - uses: actions/checkout@v2
    - uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
